### ISSUE TITLE
Как правильно коммитить?

### ISSUE THREAD

**Issue by krade88** [felocSsS/college111#3]
Алло, я не умею коммиты делать, мне нужна хелп, срочна

**Comment by felocSsS** [comment]
работай сука

**Comment by Hayrapetyan2003** [comment]
сам работай

**Comment by WorldOfPets** [comment]
Исправьте это

**Comment by WorldOfPets** [comment]
Duplicate of #

**Comment by Hayrapetyan2003** [comment]
где мой насвай?

**Comment by WorldOfPets** [comment]
[git@github.com:felocSsS/college111.git](url)

**Comment by WorldOfPets** [comment]
[git@github.com:felocSsS/college111.git](url)
